---
sdn_info:
  sdn_network_name: external

kubernetes_info:
  MASTER_IP: "{{MASTER_IP}}"
  CLUSTER_SUBNET: "{{CLUSTER_SUBNET | default('10.244.0.0/16')}}"
  MASTER_INTERNAL_IP: "{{MASTER_INTERNAL_IP | default('10.244.0.2')}}" # Will always be the second IP of CLUSTER_SUBNET
  SERVICE_CLUSTER_IP_RANGE: "{{SERVICE_CLUSTER_IP_RANGE | default('10.96.0.0/12')}}"
  K8S_DNS_DOMAIN: "{{K8S_DNS_DOMAIN | default('cluster.local')}}"
  K8S_DNS_SERVICE_IP: "{{K8S_DNS_SERVICE_IP | default('10.96.0.10')}}"
  K8S_API_SERVICE_IP: "{{K8S_API_SERVICE_IP | default('10.96.0.1')}}"

download_info:
  install_path: "{{install_path | default('C:/k')}}"

download_links:
  flannel_master_zip: "https://github.com/Microsoft/SDN/archive/master.zip"
  download_script: "https://raw.githubusercontent.com/papagalu/custom-flannel-startscript/master/download.ps1"

docker_images:
  1809: "mcr.microsoft.com/windows/nanoserver:1809"
  nanoserver: "mcr.microsoft.com/windows/nanoserver"
  servercore: "mcr.microsoft.com/windows/servercore"
